"""add original_text and extraction_status to documents

Revision ID: 0025e5e6c352
Revises: 2b496ed4ab42
Create Date: 2026-09-05 17:12:17.055601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0025e5e6c352'
down_revision: Union[str, Sequence[str], None] = '2b496ed4ab42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extraction_status', sa.String(length=32), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extraction_status')
    op.drop_column('documents', 'original_text')
    # ### end Alembic commands ###
