"""add document analysis and simplification fields

Revision ID: 07a79a5898d6
Revises: 0025e5e6c352
Create Date: 2026-09-05 21:21:48.777082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a79a5898d6'
down_revision: Union[str, Sequence[str], None] = '0025e5e6c352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('analysis_status', sa.String(length=32), server_default='not_analysed', nullable=False))
    op.add_column('documents', sa.Column('detected_terms', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('term_selection', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('simplification_status', sa.String(length=32), server_default='not_simplified', nullable=False))
    op.add_column('documents', sa.Column('simplified_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'simplified_text')
    op.drop_column('documents', 'simplification_status')
    op.drop_column('documents', 'term_selection')
    op.drop_column('documents', 'detected_terms')
    op.drop_column('documents', 'analysis_status')
    # ### end Alembic commands ###
